### ISSUE TITLE
Typo on name of files on dist

### ISSUE THREAD

**Issue by danilomelo** [bevacqua/angularjs-dragula#100]
Hi,

Please, fix typo on files angular-dragula.js to angularjs-dragula.js inside the folder dist. It is causing error on site exemple.

Thanks,
Danilo

**Comment by BrandesEric** [comment]
This causes problems with webpack/typescript environments as well, the import currently needs to be `angularjs-dragula/angular-dragula' which is cumbersome.

**Comment by bevacqua** [comment]
Fixed in `2.0.0`
