### ISSUE TITLE
Demo seems to be broken.  Script issues

### ISSUE THREAD

**Issue by Mathem8tic** [bevacqua/angularjs-dragula#103]
http://bevacqua.github.io/angularjs-dragula/

**Comment by christianhg** [comment]
Probably broken by 0586c6158c14544e7b32a7a6dae8f9fc2f5b53e5.

**Comment by assumption** [comment]
Specifically, the demo tries to request 'angularjs-dragula.js' in [dist](https://github.com/bevacqua/angularjs-dragula/tree/master/dist), but the file is still named '[angular-dragula.js](https://github.com/bevacqua/angularjs-dragula/blob/master/dist/angular-dragula.js)'

**Comment by danilomelo** [comment]
I've been created a issue for this too here #100

**Comment by bevacqua** [comment]
Fixed in `2.0.0`
