### ISSUE TITLE
Demo page broken

### ISSUE THREAD

**Issue by hackerhasid** [bevacqua/angularjs-dragula#109]
examples do not work and there are console errors in chrome
![image](https://cloud.githubusercontent.com/assets/797379/24482947/dd07fa60-14c2-11e7-8883-07f330e2ea6f.png)

slack link directs to error page

**Comment by scripterkaran** [comment]
Yes

**Comment by clemens-tolboom** [comment]
Demo is still broken

**Comment by timobehrens** [comment]
Is only the demo broken, or the whole library?

**Comment by kumorig** [comment]
The library works fine, but it sure makes you wonder.

**Comment by hackerhasid** [comment]
agreed. when looking for a solution for drag&drop i stumbled on angular-dragula. but with a broken demo page it's not clear if it's worth the effort or better off moving along.

**Comment by douglaslmiller** [comment]
The file in the /dist/ directory is named angular-dragula.js. It looks like there was a rename in the last commit and it was missed since everywhere else it was renamed to angularjs-dragula.js. So if you either rename the file, or change the script src it will work.

**Comment by torzuoliH** [comment]
New demo guys: https://bevacqua.github.io/dragula/

**Comment by bevacqua** [comment]
Fixed in `2.0.0`
