### ISSUE TITLE
Change Github demo link

### ISSUE THREAD

**Issue by torzuoliH** [bevacqua/angularjs-dragula#117]
Nothing really important, but current Demo link on Github page is [this one](http://bevacqua.github.io/angular-dragula) which is not working.

Most recent link seems to be [this one](http://bevacqua.github.io/angularjs-dragula).

By the way, as said #109, demo is not working.

**Comment by bevacqua** [comment]
Fixed

**Comment by HZooly** [comment]
Thanks!
