### ISSUE TITLE
models are lost when inside ng-if

### ISSUE THREAD

**Issue by abderrahmane-tj** [bevacqua/angularjs-dragula#62]
Hi there,

In the following example I have to sections : 
- one containing templates
- and another one containing a table

the templates section is used to build the table and fill it with items.
templates are either Rows, or Items.

if the table contains no rows, I do not want to have the template items on the DOM altogether.
so I am wrapping the template area with ngif.
trouble is, dragula-model won't reflect what really is in the templates model when you drag an item from the templates section.

https://plnkr.co/edit/sQPfDeUqfJ3FpPvVElp6?p=preview

**Comment by kruny1001** [comment]
"ng-if" creates an isolate scope. If you intend to show or hide a target element, use ng-show and ng-hide.

**Comment by abderrahmane-tj** [comment]
@kruny1001 I know what ngif dose and what ngshow does. i want to know if i could make it work with ngif
